# Generated by Django 3.1.7 on 2021-05-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adsubject_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminsubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100, null=True)),
                ('subjectname', models.CharField(max_length=30)),
                ('total_lectures', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='adsubject',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='population',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
